### ISSUE TITLE
Removing duplicates in titles list

### ISSUE THREAD

**Issue by jmuru** [KyleLH/SCHistory#1]
Sup! I'm working on removing duplicates from the list but i'm a bit confused as to how chrome is adding each title to the list...

```
        if (song.title !== undefined) {
            var all;
            chrome.storage.local.get("SCHistory", function (items) {
                if (items.SCHistory === undefined) items.SCHistory = [];

                items.SCHistory.push(song);
                chrome.storage.local.set({"SCHistory": items.SCHistory});
            }); 
        }
```

it seems to me that `chrome.storage.local.set()` handles the updating of the list in the popup, but is there any way to access the whole list of titles before that?

I initially though `items.SCHistory` held all of the titles in a list but it seems as if it does not. Idk i may be just flat out wrong.

**Comment by jmuru** [comment]
wait or should i be removing duplicates in the popup.js, by iterating through xs and removing them there?

**Comment by avegancafe** [comment]
Hey, I actually just implemented removing duplicates as well on the react branch. `items.SCHistory` does indeed contain all of the songs in localstorage; the `chrome.storage.local.set()` function takes in an object and updates each of the keys in the provided object to the specified value. Honestly I could have also done `chrome.storage.local.set(items)`, since items is just `{ SCHistory: [/*some list*/] }`.

**Comment by jmuru** [comment]
nice!!!
